import type { Metadata } from "next";
import "./globals.css";

import { Modals } from "@/components/modals";
import { JotaiProvider } from "@/components/jotai-provider";
import { Providers } from "./Provider";

import { Toaster } from "@/components/ui/sonner";
import { SheetProvider } from "@/providers/sheet-provider";

import { ThemeProvider } from "@/components/providers/theme-provider";

import { GeistSans } from "geist/font/sans";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${GeistSans.className}`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <JotaiProvider>
            <Providers>
              <SheetProvider />
              <Toaster />
              <Modals />
              {children}
            </Providers>
          </JotaiProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
