import type { Metadata } from "next";
import "./globals.css";

import { Modals } from "@/components/modals";
import { JotaiProvider } from "@/components/jotai-provider";
import { Providers } from "./Provider";

import { Toaster } from "@/components/ui/sonner";
import { SheetProvider } from "@/providers/sheet-provider";

import { FontProvider } from "@/context/font-context";
import { RouteGuard } from "@/components/RouteGuard";
import { ThemeProvider } from "@/components/providers/theme-provider";

import { fontConfig } from "@/lib/fonts"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const fontVariables = Object.values(fontConfig)
    .map((config) => config.font.variable)
    .join(" ");

  return (
    <html lang="en" suppressHydrationWarning className={`${fontVariables} font-inter`}>
      <body>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <FontProvider>
            <JotaiProvider>
              <Providers>
                <SheetProvider />
                <Toaster />
                <Modals />
                <RouteGuard>
                  {children}
                </RouteGuard>
              </Providers>
            </JotaiProvider>
          </FontProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
